Added AsyncFunctionDef visitor to make compatible with async functions
HunterMcGushion/docstr_coverage pull request #116
Opened 2022-08-30 15:25 UTC by caffeinatedMike

Allows the tool to properly detect async functions and factor in their docstrings in coverage/missing reports. Prior to this fix, async functions were complete ignored and not factoring into overall docstring coverage, which caused skewed coverage percentages and async functions potentially being left undocumented.

2022-08-30 17:39 UTC, MiWeiss commented
Thanks a lot for this PR: Wow - I'm not sure if that's a bug or a feature; but in either case, it's high priority :-)

I'd like to merge this asap.  There are two things missing:
- *Unit tests* would you mind adding some unit tests; including ones that test naming-convention based *ignoring* of async functions (e.g. private `async def _do_something()`)? While I trust that you locally tested your change, these unit tests will defend against regressions and make sure your change remains functional in the future.
- *Linting* There is still an `isort` issue.

2022-08-30 17:40 UTC, MiWeiss requested changes
See comment above

2022-08-30 18:44 UTC, HunterMcGushion commented
Nice catch, @caffeinatedMike! After making the changes requested by @MiWeiss, let's get this merged.

2022-08-30 18:47 UTC, caffeinatedMike commented
@MiWeiss My pleasure! I always enjoying being able to contribute to the open-source tools I use. I've corrected the isort issue. Working on adding the tests now.

2022-08-30 22:04 UTC, caffeinatedMike commented
@MiWeiss @HunterMcGushion Tests added & everything looks good!

2022-08-30 22:22 UTC, HunterMcGushion commented on tests/excused_samples/fully_excused.py
> +    # docstr-coverage:excuse `...almost as lazy as async functions...`
Nice

2022-08-30 22:29 UTC, HunterMcGushion commented
This looks great to me. Does it get your seal of approval, @MiWeiss?

2022-08-31 06:08 UTC, MiWeiss approved these changes
lgtm

thanks a lot @caffeinatedMike for your contribution

2022-08-31 06:09 UTC, merged